
///////
// Network + Layer Configuration.
// File automatically generated by convert_caffemodel.py
// from deploy.prototxt and modified.caffemodel
// (c) 2016 David Gschwend
///////

#include "network.hpp"
network_t *get_network_config() {
  network_t *net = new network_t(5, 420);

  //                                                                            UPD
  // Layer Attributes: ( NAME   , TYPE      ,   W,   H,   CI,  CO, K, P, S) EXP MEM POOL Type
  addLayer(net, layer_t("cnv1  ", LAYER_CONV,   8,   8,    3,   8, 3, 1, 2), 0,  1, POOL_NONE);
  addLayer(net, layer_t("f/s1  ", LAYER_CONV,   4,   4,    8,   2, 1, 0, 1), 0,  1, POOL_NONE);
  addLayer(net, layer_t("f/e1  ", LAYER_CONV,   4,   4,    2,   4, 1, 0, 1), 1,  1, POOL_NONE);
  addLayer(net, layer_t("f/e3  ", LAYER_CONV,   4,   4,    2,   4, 3, 1, 1), 1,  0, POOL_NONE);
  addLayer(net, layer_t("cnv10 ", LAYER_CONV,   4,   4,    8,  10, 1, 0, 1), 0,  1, POOL_GLOBAL);

  net->num_weights = 420;
  const char* filename = "weights.bin";
  loadWeightsFromFile(net, filename);
  return net;
}
