
///////
// Network + Layer Configuration.
// File automatically generated by convert_caffemodel.py
// from deploy.prototxt and modified.caffemodel
// (c) 2016 David Gschwend
///////

#ifndef _NETWORK_H_
#define _NETWORK_H_

// Size Limits for this Network
const int MAX_NUM_LAYERS = 5;
const int MAX_WEIGHTS_PER_LAYER = 224;
const int MAX_IMAGE_CACHE_SIZE = 128;
const int MAX_INPUT_PER_LAYER = 192;
const int MAX_NUM_CHOUT = 10;
const int MAX_DIMENSION = 8;
const int MAX_CHANNELS = 10;

const int TOTAL_NUM_WEIGHTS = 420;
const int TOTAL_NUM_INPUTS = 512;
const int TOTAL_NUM_OUTPUTS = 448;
const int TOTAL_DRAM_IO = 1380;

// Mean Pixel for ImageNet Data
const float MEAN_R = 104;
const float MEAN_G = 117;
const float MEAN_B = 123;

const int DRAM_DEPTH = 1049216;
const float TEST_RESULT_EXPECTED = 23.32;

// include after definitions to allow bit-width calculations
#include "netconfig.hpp"

network_t *get_network_config();

#endif
