
///////
// Network + Layer Configuration.
// File automatically generated by convert_caffemodel.py
// from deploy.prototxt and modified.caffemodel
// (c) 2016 David Gschwend
///////

#include "network.hpp"
network_t *get_network_config() {
  network_t *net = new network_t(26, 1577800);

  //                                                                            UPD
  // Layer Attributes: ( NAME   , TYPE      ,   W,   H,   CI,  CO, K, P, S) EXP MEM POOL Type
  addLayer(net, layer_t("cnv1  ", LAYER_CONV, 256, 256,    3,  64, 3, 1, 2), 0,  1, POOL_NONE);
  addLayer(net, layer_t("f2/s1 ", LAYER_CONV, 128, 128,   64,  16, 3, 1, 2), 0,  1, POOL_NONE);
  addLayer(net, layer_t("f2/e1 ", LAYER_CONV,  64,  64,   16,  64, 1, 0, 1), 1,  1, POOL_NONE);
  addLayer(net, layer_t("f2/e3 ", LAYER_CONV,  64,  64,   16,  64, 3, 1, 1), 1,  0, POOL_NONE);
  addLayer(net, layer_t("f3/s1 ", LAYER_CONV,  64,  64,  128,  16, 1, 0, 1), 0,  1, POOL_NONE);
  addLayer(net, layer_t("f3/e1 ", LAYER_CONV,  64,  64,   16,  64, 1, 0, 1), 1,  1, POOL_NONE);
  addLayer(net, layer_t("f3/e3 ", LAYER_CONV,  64,  64,   16,  64, 3, 1, 1), 1,  0, POOL_NONE);
  addLayer(net, layer_t("f4/s1 ", LAYER_CONV,  64,  64,  128,  32, 3, 1, 2), 0,  1, POOL_NONE);
  addLayer(net, layer_t("f4/e1 ", LAYER_CONV,  32,  32,   32, 128, 1, 0, 1), 1,  1, POOL_NONE);
  addLayer(net, layer_t("f4/e3 ", LAYER_CONV,  32,  32,   32, 128, 3, 1, 1), 1,  0, POOL_NONE);
  addLayer(net, layer_t("f5/s1 ", LAYER_CONV,  32,  32,  256,  32, 1, 0, 1), 0,  1, POOL_NONE);
  addLayer(net, layer_t("f5/e1 ", LAYER_CONV,  32,  32,   32, 128, 1, 0, 1), 1,  1, POOL_NONE);
  addLayer(net, layer_t("f5/e3 ", LAYER_CONV,  32,  32,   32, 128, 3, 1, 1), 1,  0, POOL_NONE);
  addLayer(net, layer_t("f6/s1 ", LAYER_CONV,  32,  32,  256,  64, 3, 1, 2), 0,  1, POOL_NONE);
  addLayer(net, layer_t("f6/e1 ", LAYER_CONV,  16,  16,   64, 256, 1, 0, 1), 1,  1, POOL_NONE);
  addLayer(net, layer_t("f6/e3 ", LAYER_CONV,  16,  16,   64, 256, 3, 1, 1), 1,  0, POOL_NONE);
  addLayer(net, layer_t("f7/s1 ", LAYER_CONV,  16,  16,  512,  64, 1, 0, 1), 0,  1, POOL_NONE);
  addLayer(net, layer_t("f7/e1 ", LAYER_CONV,  16,  16,   64, 256, 1, 0, 1), 1,  1, POOL_NONE);
  addLayer(net, layer_t("f7/e3 ", LAYER_CONV,  16,  16,   64, 256, 3, 1, 1), 1,  0, POOL_NONE);
  addLayer(net, layer_t("f8/s1 ", LAYER_CONV,  16,  16,  512,  64, 1, 0, 1), 0,  1, POOL_NONE);
  addLayer(net, layer_t("f8/e1 ", LAYER_CONV,  16,  16,   64, 256, 1, 0, 1), 1,  1, POOL_NONE);
  addLayer(net, layer_t("f8/e3 ", LAYER_CONV,  16,  16,   64, 256, 3, 1, 1), 1,  0, POOL_NONE);
  addLayer(net, layer_t("f9/s1 ", LAYER_CONV,  16,  16,  512,  64, 1, 0, 1), 0,  1, POOL_NONE);
  addLayer(net, layer_t("f9/e1 ", LAYER_CONV,  16,  16,   64, 256, 1, 0, 1), 1,  1, POOL_NONE);
  addLayer(net, layer_t("f9/e3 ", LAYER_CONV,  16,  16,   64, 256, 3, 1, 1), 1,  0, POOL_NONE);
  addLayer(net, layer_t("cnv10 ", LAYER_CONV,  16,  16,  512,1000, 1, 0, 1), 0,  1, POOL_GLOBAL);

  net->num_weights = 1577800;
  const char* filename = "weights.bin";
  loadWeightsFromFile(net, filename);
  return net;
}
